[styles.battery]
high_battery_color = "#a6e3a1"
low_battery_color = "#f38ba8"
medium_battery_color = "#f9e2af"

[styles.cpu]
all_entry_color = "#f5e0dc"
avg_entry_color = "#eba0ac"
cpu_core_colors = ["#74c7ec", "#a6e3a1", "#cba6f7", "#f38ba8", "#f9e2af", "#fab387"]

[styles.graphs]
graph_color = "#a6adc8"
legend_text = { color = "#a6adc8" }

[styles.memory]
arc_color = "#89dceb"
cache_color = "#f38ba8"
gpu_colors = ["#74c7ec", "#a6e3a1", "#cba6f7", "#f38ba8", "#f9e2af", "#fab387"]
ram_color = "#a6e3a1"
swap_color = "#fab387"

[styles.network]
rx_color = "#a6e3a1"
rx_total_color = "#89dceb"
tx_color = "#f38ba8"
tx_total_color = "#a6e3a1"

[styles.tables]
headers = { color = "#f5e0dc" }

[styles.widgets]
border_color = "#585b70"
disabled_text = { color = "#1e1e2e" }
selected_border_color = "#f5c2e7"
selected_text = { bg_color = "#cba6f7", color = "#11111b" }
text = { color = "#cdd6f4" }
widget_title = { color = "#f2cdcd" }
