- name: Shell
  hosts: localhost
  vars:
    ansible_connection: local

  tasks:
    # - name: Install homebrew
    #   ansible.builtin.shell:
    #     cmd: |
    #       /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

    # - name: Install zsh
    #   community.general.homebrew:
    #     name: "{{ item }}"
    #     state: present
    #   with_items:
    #     - zsh
    #     - dotdrop

    # - name: Set zsh as a default shell
    #   ansible.builtin.shell:
    #     cmd: |
    #       sudo sh -c "echo $(which zsh) >> /etc/shells"
    #       chsh -s $(which zsh)

    - name: Install oh-my-zsh
      ignore_errors: true
      ansible.builtin.shell:
        cmd: |
          sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: Install dotfiles
      ignore_errors: true
      ansible.builtin.shell:
        cmd: |
          dotdrop -c "../dotdrop.yaml" -p base install -f
